### ISSUE TITLE
Research CSS framework that isn't Bootstrap

### ISSUE THREAD

**Issue by brian-presta** [chulopapi/safeTravels#3]

**Comment by chulopapi** [comment]
There are two possible CSS framework that we can work with:
1. Materialize:  https://materializecss.com/

2. tailwindcss:  https://tailwindcss.com/

**Comment by chulopapi** [comment]
Using Tailwind via CDN

Before using the CDN build, please note that many of the features that make Tailwind CSS great are not available without incorporating Tailwind into your build process.

You can't customize Tailwind's default theme
You can't use any directives like @apply, @variants, etc.
You can't enable features like group-hover

    You can't install third-party plugins

To get the most out of Tailwind, you really should install it via npm.

To pull in Tailwind for quick demos or just giving the framework a spin, grab the latest default configuration build via CDN:

<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

**Comment by chulopapi** [comment]
HTML Setup

Next you just have to make sure you link the files properly in your webpage. Generally it is wise to import javascript files at the end of the body to reduce page load time. Follow the example below on how to import Materialize into your webpage.

  <!DOCTYPE html>
  <html>
    <head>
      
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

      
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>

      
      <script type="text/javascript" src="js/materialize.min.js"></script>
    </body>
  </html>
        


    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

**Comment by chulopapi** [comment]
Project Structure for Materialize :  Directory example:


  MyWebsite/
  |--css/
  |  |--materialize.css
  |
  |--fonts/
  |  |--roboto/
  |
  |--js/
  |  |--materialize.js
  |
  |--index.html

**Comment by brian-presta** [comment]
Looks cool! Given that Tailwind talks about not having all it's features available if we implement it with a CDN link, I'd say we should probably go with Materialize

**Comment by chulopapi** [comment]
Yes, I was asking around today and it seems that materialize is CSS framework to use.   They have a couple of template deployments as well that are pretty basic and we can expand if needed.

**Comment by armydavid** [comment]
Completed - Team decided to use materialized
